language: ruby
rvm:
- 2.1.3
bundler_args: "--without production"
before_install:
- gem update --system
- gem --version
script:
- bundle exec rake db:drop db:create db:migrate
- bundle exec rspec spec
env:
  global:
    secure: XrfB28vU0Gumfh6FfYS50bu00xBjRKT5qPtlqqNQJglS/VCNBtLvc6JCjevya3fpE4UwTxt0u31weh45qUWvnN8Oq7CjFNWpnLovrhd4RnRyPCIq7Hj0dFBihzlV7uS3NVDKfpRVFRmUkpPP8vWXwvZ1k/GnN0ZvxQhj50BZ4mk=
deploy:
  provider: heroku
  api_key:
    secure: WW5lddpKZKs9TW6xg4l1PCOY3LsiiY66wQEc6t8MQCGyt5eUdtM8KOdx2Qu+KH/cLFSu+BpIoKTLJMeS0rN2puy/kSj7QVJKd8gVPEjV2bpOky8cheYNZ0KqsQ4j+cbe7pBD18xs+nQup1I5SguKG2JG35w/JJpc3P8izc4XHJM=
  app: streaming
  on:
    repo: pyarbz/streaming
