language: ruby
rvm:
- 2.1.2
bundler_args: "--without production"
before_install:
- gem update --system
- gem --version
- sudo apt-get install build-essential libopencv-contrib-dev
- curl -sL https://github.com/Itseez/opencv/archive/2.4.9.zip > opencv.zip
- unzip opencv.zip
- rm opencv.zip
- mkdir opencv-build
- cd opencv-build
- cmake -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_DOCS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_opencv_java=OFF -DBUILD_JASPER=ON -DWITH_JASPER=ON -DBUILD_ZLIB=ON -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DWITH_OPENEXR=OFF -DBUILD_PNG=ON -DWITH_PNG=ON -DWITH_TIFF=ON -DBUILD_TIFF=ON -DWITH_WEBP=OFF -DWITH_JPEG=ON -DBUILD_JPEG=ON ../opencv-2.4.9/
- sudo make install
- cd ..
script:
- bundle exec rake db:drop db:create db:migrate
- bundle exec rspec spec
after_script:
- rm -rf opencv-build
env:
  global:
    secure: XrfB28vU0Gumfh6FfYS50bu00xBjRKT5qPtlqqNQJglS/VCNBtLvc6JCjevya3fpE4UwTxt0u31weh45qUWvnN8Oq7CjFNWpnLovrhd4RnRyPCIq7Hj0dFBihzlV7uS3NVDKfpRVFRmUkpPP8vWXwvZ1k/GnN0ZvxQhj50BZ4mk=
deploy:
  provider: heroku
  buildpack: https://github.com/lilibethdlc/heroku-buildpack-ruby-opencv.git
  api_key:
    secure: Qu77fhluD4BDUreNMMEHgqDCVDjLpgj1e5Zg6LlOC2CbUCeKZloukxFEDdNyHLQuHvn8eh7FG7LSuS1L6iLez3GpZweS2+F8Ze0FY7PWC0oYeUjcc/SaJmdug8uacQ45ZQur9/4kIBpOgID3IUwaO2cqCcSahBWswqXRT4AnoT8=
  app: animeshows
  on:
    repo: pyarbz/streaming
