language: ruby
rvm:
- 2.1.2
bundler_args: "--without development production"
before_install:
  - gem update --system
  - gem --version
script:
  - bundle exec rake db:drop db:create db:migrate
#  - bundle exec rake db:test:prepare
  - bundle exec rspec spec
deploy:
  provider: heroku
  api_key:
    secure: Qu77fhluD4BDUreNMMEHgqDCVDjLpgj1e5Zg6LlOC2CbUCeKZloukxFEDdNyHLQuHvn8eh7FG7LSuS1L6iLez3GpZweS2+F8Ze0FY7PWC0oYeUjcc/SaJmdug8uacQ45ZQur9/4kIBpOgID3IUwaO2cqCcSahBWswqXRT4AnoT8=
  app: animeshows
  on:
    repo: pyarbz/streaming
  run:
    - "rake db:migrate"
